In [1]:
import tensorflow as tf
import tensorflow_hub as hub

import os


In [2]:
tf.__version__

'1.15.0'

In [3]:
os.environ["TFHUB_CACHE_DIR"] = '/space/engineering/tfhub_modules'

In [4]:
##restricting no of gpus
gpus = tf.config.experimental.list_physical_devices('GPU')
device_to_use = gpus[2]
tf.config.experimental.set_memory_growth(device_to_use,True)
tf.config.experimental.set_visible_devices(device_to_use, 'GPU')
print(tf.config.experimental.get_visible_devices('GPU'))

[PhysicalDevice(name='/physical_device:GPU:2', device_type='GPU')]


In [5]:
sess = tf.Session()

In [6]:
!pwd


/var/extra/users/jgeorge/tf2.0


In [6]:
OUTPUT_PATH="/var/extra/users/jgeorge/tf2.0/USE/large"

In [7]:
# module = hub.Module("https://tfhub.dev/google/universal-sentence-encoder/2")
# module = hub.load("https://tfhub.dev/google/universal-sentence-encoder/3")
# module4 = hub.load("https://tfhub.dev/google/universal-sentence-encoder/4")

# module = hub.load("https://tfhub.dev/google/universal-sentence-encoder-large/3")
module = hub.load("https://tfhub.dev/google/universal-sentence-encoder-large/5")


Instructions for updating:
If using Keras pass *_constraint arguments to layers.


Instructions for updating:
If using Keras pass *_constraint arguments to layers.


In [5]:
module.tensorflow_version

'1.15.0'

In [8]:
text = tf.placeholder(tf.string, [None],name='input_text')
embedding = module(text)

In [7]:
embedding

<tf.Tensor 'StatefulPartitionedCall_1:0' shape=(?, 512) dtype=float32>

In [20]:
embedding1

{'outputs': <tf.Tensor 'StatefulPartitionedCall_1:0' shape=(?, 512) dtype=float32>}

In [7]:
text1 = tf.placeholder(tf.string,name="input_text1")
embedding1 = module(text1)

In [8]:
text2 = tf.placeholder(tf.string,None)
embedding2 = module4(text2)

In [9]:
normalize_t1 = tf.nn.l2_normalize(embedding1['outputs'],1) 

In [26]:
mod1 = tf.reduce_sum(normalize_t1)

In [27]:
sess.run(mod1,feed_dict={text1:["talk to an me"]})

14.0

In [10]:
normalize_t2 = tf.nn.l2_normalize(embedding2,1) 

In [11]:
# https://stackoverflow.com/questions/43357732/how-to-calculate-the-cosine-similarity-between-two-tensors
similarity = tf.reduce_sum(tf.multiply(normalize_t1,normalize_t2))

In [9]:
init_op = tf.group([tf.global_variables_initializer(), 
tf.tables_initializer()])

In [10]:
sess.run(init_op)

In [11]:
text = tf.placeholder(tf.string, [None],name='input_text')

In [12]:
out = table.lookup(text)

In [15]:
sess.run(out,feed_dict={text:["hi","jithin"]})

array([10, 20])

In [18]:
sess.run(similarity,feed_dict={text1:["im happy_dumm1212"],text2:["im happy_dumm1212]"]})

1.0000001

In [21]:
sess.run(embedding1,feed_dict={text1:["im happy_dumm1212"]})

{'outputs': array([[-6.55069388e-03, -8.08349326e-02,  8.98723677e-02,
          1.85724273e-02,  9.66336802e-02, -4.06424236e-03,
          4.70154323e-02, -2.27858908e-02,  5.66757508e-02,
          1.43694924e-02,  7.02791512e-02,  1.80836823e-02,
          5.11801578e-02,  1.30773082e-01, -6.08522817e-03,
         -3.23820040e-02, -1.56024611e-02,  3.13060805e-02,
         -1.24757225e-03, -7.72922486e-02, -5.73251434e-02,
          4.08432335e-02,  2.71441378e-02,  4.07955125e-02,
         -2.38824356e-02,  3.03580868e-03,  2.02206802e-02,
         -2.20513232e-02,  2.39775740e-02,  1.58273894e-02,
          1.42639305e-03,  8.02937336e-03,  4.56940010e-02,
          4.70260251e-03,  2.13103760e-02, -3.59224193e-02,
         -4.36784141e-02,  5.55752255e-02, -2.90047880e-02,
          3.49619500e-02,  2.84531545e-02, -4.99228295e-03,
         -1.41794337e-02,  5.06731495e-02, -1.34483613e-02,
         -4.21394594e-02, -7.58662149e-02, -4.16629016e-02,
         -1.93628911e-02, -1.

In [22]:
sess.run(embedding2,feed_dict={text2:["im happy_dumm1212"]})

array([[-6.55069388e-03, -8.08349326e-02,  8.98723677e-02,
         1.85724273e-02,  9.66336802e-02, -4.06424236e-03,
         4.70154323e-02, -2.27858908e-02,  5.66757508e-02,
         1.43694924e-02,  7.02791512e-02,  1.80836823e-02,
         5.11801578e-02,  1.30773082e-01, -6.08522817e-03,
        -3.23820040e-02, -1.56024611e-02,  3.13060805e-02,
        -1.24757225e-03, -7.72922486e-02, -5.73251434e-02,
         4.08432335e-02,  2.71441378e-02,  4.07955125e-02,
        -2.38824356e-02,  3.03580868e-03,  2.02206802e-02,
        -2.20513232e-02,  2.39775740e-02,  1.58273894e-02,
         1.42639305e-03,  8.02937336e-03,  4.56940010e-02,
         4.70260251e-03,  2.13103760e-02, -3.59224193e-02,
        -4.36784141e-02,  5.55752255e-02, -2.90047880e-02,
         3.49619500e-02,  2.84531545e-02, -4.99228295e-03,
        -1.41794337e-02,  5.06731495e-02, -1.34483613e-02,
        -4.21394594e-02, -7.58662149e-02, -4.16629016e-02,
        -1.93628911e-02, -1.65836439e-02, -4.47860844e-0

In [11]:
sess.run(embedding,feed_dict={text:["talk to an agent"]})

array([[ 5.42287901e-02, -9.49551463e-02,  4.66933846e-03,
        -3.35001498e-02, -3.67378145e-02, -4.07931209e-02,
         6.11383282e-02, -5.53360730e-02, -2.63383593e-02,
        -8.41903165e-02, -2.94553600e-02, -2.54329015e-02,
         1.82801038e-02, -4.35052207e-03, -3.31694037e-02,
         2.63817813e-02,  9.69651192e-02, -5.68300039e-02,
         4.03156132e-02,  1.64154526e-02, -4.03435305e-02,
        -9.76875722e-02, -5.79786226e-02, -6.92774504e-02,
        -5.92130469e-03,  1.60682900e-03,  3.15396301e-02,
        -8.58933255e-02, -2.95109414e-02, -1.29586235e-02,
        -3.26752178e-02, -1.53197441e-02, -2.22712364e-02,
         1.29994284e-03, -3.43569145e-02,  7.00082630e-02,
         1.90935545e-02, -3.69642861e-02,  3.68834361e-02,
        -1.24806166e-02,  3.60590704e-02,  4.87940460e-02,
        -1.61846150e-02,  3.80572379e-02,  4.91064526e-02,
         7.03401817e-03,  4.49982509e-02,  2.40888577e-02,
         2.61179563e-02, -6.86665028e-02,  1.71266235e-0

In [12]:
use_output_path1= os.path.join(OUTPUT_PATH,'v5')

In [14]:
use_output_path1

'/var/extra/users/jgeorge/tf2.0/USE_1.12/v3'

In [16]:
text

<tf.Tensor 'Placeholder:0' shape=(?,) dtype=string>

In [17]:
embedding

{'outputs': <tf.Tensor 'StatefulPartitionedCall:0' shape=(?, 512) dtype=float32>}

In [13]:
tf.saved_model.simple_save(sess,use_output_path1,inputs={'input_text':text},outputs={'embedding':embedding},
                           legacy_init_op=tf.tables_initializer())

Instructions for updating:
This function will only be available through the v1 compatibility library as tf.compat.v1.saved_model.simple_save.


Instructions for updating:
This function will only be available through the v1 compatibility library as tf.compat.v1.saved_model.simple_save.


Instructions for updating:
This function will only be available through the v1 compatibility library as tf.compat.v1.saved_model.utils.build_tensor_info or tf.compat.v1.saved_model.build_tensor_info.


Instructions for updating:
This function will only be available through the v1 compatibility library as tf.compat.v1.saved_model.utils.build_tensor_info or tf.compat.v1.saved_model.build_tensor_info.


INFO:tensorflow:Assets added to graph.


INFO:tensorflow:Assets added to graph.


INFO:tensorflow:No assets to write.


INFO:tensorflow:No assets to write.


Type is unsupported, or the types of the items don't match field type in CollectionDef. Note this is a warning and probably safe to ignore.
'list' object has no attribute 'name'


Type is unsupported, or the types of the items don't match field type in CollectionDef. Note this is a warning and probably safe to ignore.
'list' object has no attribute 'name'


INFO:tensorflow:SavedModel written to: /var/extra/users/jgeorge/tf2.0/USE/large/v5/saved_model.pb


INFO:tensorflow:SavedModel written to: /var/extra/users/jgeorge/tf2.0/USE/large/v5/saved_model.pb


In [15]:
tf.saved_model.simple_save(sess,use_output_path1,inputs={'input_text':text},outputs={'embedding':embedding['outputs']},
                           legacy_init_op=tf.tables_initializer())

Instructions for updating:
This function will only be available through the v1 compatibility library as tf.compat.v1.saved_model.simple_save.


Instructions for updating:
This function will only be available through the v1 compatibility library as tf.compat.v1.saved_model.simple_save.


Instructions for updating:
This function will only be available through the v1 compatibility library as tf.compat.v1.saved_model.utils.build_tensor_info or tf.compat.v1.saved_model.build_tensor_info.


Instructions for updating:
This function will only be available through the v1 compatibility library as tf.compat.v1.saved_model.utils.build_tensor_info or tf.compat.v1.saved_model.build_tensor_info.


INFO:tensorflow:Assets added to graph.


INFO:tensorflow:Assets added to graph.


INFO:tensorflow:No assets to write.


INFO:tensorflow:No assets to write.


Type is unsupported, or the types of the items don't match field type in CollectionDef. Note this is a warning and probably safe to ignore.
'list' object has no attribute 'name'


Type is unsupported, or the types of the items don't match field type in CollectionDef. Note this is a warning and probably safe to ignore.
'list' object has no attribute 'name'


INFO:tensorflow:SavedModel written to: /var/extra/users/jgeorge/tf2.0/USE_1.12/v3/saved_model.pb


INFO:tensorflow:SavedModel written to: /var/extra/users/jgeorge/tf2.0/USE_1.12/v3/saved_model.pb


In [16]:
builder = tf.saved_model.builder.SavedModelBuilder(use_output_path1)

In [28]:
tf.saved_model.build_tensor_info(embedding['outputs'])

name: "StatefulPartitionedCall:0"
dtype: DT_FLOAT
tensor_shape {
  dim {
    size: -1
  }
  dim {
    size: 512
  }
}

In [17]:
prediction_signature = tf.saved_model.predict_signature_def(inputs={'input_text':text},outputs={'embedding':embedding['outputs']})

Instructions for updating:
This function will only be available through the v1 compatibility library as tf.compat.v1.saved_model.utils.build_tensor_info or tf.compat.v1.saved_model.build_tensor_info.


Instructions for updating:
This function will only be available through the v1 compatibility library as tf.compat.v1.saved_model.utils.build_tensor_info or tf.compat.v1.saved_model.build_tensor_info.


In [18]:
prediction_signature

inputs {
  key: "input_text"
  value {
    name: "input_text:0"
    dtype: DT_STRING
    tensor_shape {
      dim {
        size: -1
      }
    }
  }
}
outputs {
  key: "embedding"
  value {
    name: "StatefulPartitionedCall:0"
    dtype: DT_FLOAT
    tensor_shape {
      dim {
        size: -1
      }
      dim {
        size: 512
      }
    }
  }
}
method_name: "tensorflow/serving/predict"

In [18]:
tf.saved_model.signature_constants.DEFAULT_SERVING_SIGNATURE_DEF_KEY

'serving_default'

In [22]:
tf.saved_model.tag_constants.SERVING

'serve'

In [23]:
EMBEDDING_SIG_DEF_KEY='embedding'

In [29]:
builder.add_meta_graph_and_variables(sess,tags=[tf.saved_model.tag_constants.SERVING],
                                     signature_def_map={tf.saved_model.DEFAULT_SERVING_SIGNATURE_DEF_KEY:prediction_signature,
                                                       EMBEDDING_SIG_DEF_KEY:prediction_signature},
                                     main_op=tf.group([tf.tables_initializer()]))

INFO:tensorflow:No assets to save.


INFO:tensorflow:No assets to save.


INFO:tensorflow:No assets to write.


INFO:tensorflow:No assets to write.


Type is unsupported, or the types of the items don't match field type in CollectionDef. Note this is a warning and probably safe to ignore.
'list' object has no attribute 'name'


Type is unsupported, or the types of the items don't match field type in CollectionDef. Note this is a warning and probably safe to ignore.
'list' object has no attribute 'name'


In [30]:
builder.save()

INFO:tensorflow:SavedModel written to: /var/extra/users/jgeorge/tf2.0/USE_1.12/v3/saved_model.pb


INFO:tensorflow:SavedModel written to: /var/extra/users/jgeorge/tf2.0/USE_1.12/v3/saved_model.pb


b'/var/extra/users/jgeorge/tf2.0/USE_1.12/v3/saved_model.pb'